// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "shop-product-service",
    "version": "1"
  },
  "paths": {
    "/product/available": {
      "get": {
        "summary": "getProductsInStock",
        "description": "",
        "operationId": "getProductsInStock.get.product/available",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "getProductInStock",
        "description": "",
        "operationId": "getProductInStock.get.product/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/product": {
      "put": {
        "summary": "upsertProductInStock",
        "description": "",
        "operationId": "upsertProductInStock.put.product",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PutUpsertProductInStockBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "id",
        "description",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductInStock": {
      "properties": {
        "count": {
          "title": "ProductInStock.count"
        }
      },
      "required": [
        "count"
      ],
      "additionalProperties": false,
      "title": "ProductInStock",
      "type": "object"
    },
    "ImportedProductInStock": {
      "properties": {
        "Title": {
          "title": "ImportedProductInStock.Title",
          "type": "string"
        },
        "Description": {
          "title": "ImportedProductInStock.Description",
          "type": "string"
        },
        "Price": {
          "title": "ImportedProductInStock.Price",
          "type": "string"
        },
        "Count": {
          "title": "ImportedProductInStock.Count",
          "type": "string"
        }
      },
      "required": [
        "Title",
        "Description",
        "Price",
        "Count"
      ],
      "additionalProperties": false,
      "title": "ImportedProductInStock",
      "type": "object"
    },
    "StockItem": {
      "properties": {
        "productId": {
          "title": "StockItem.productId",
          "type": "string"
        },
        "count": {
          "title": "StockItem.count",
          "type": "number"
        }
      },
      "required": [
        "productId",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockItem",
      "type": "object"
    },
    "PutUpsertProductInStockBody": {
      "$ref": "#/definitions/Product",
      "title": "PutUpsertProductInStockBody"
    }
  },
  "securityDefinitions": {}
};