// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "shop-be",
    "version": "1"
  },
  "paths": {
    "/product/available": {
      "get": {
        "summary": "getProductsInStock",
        "description": "",
        "operationId": "getProductsInStock.get.product/available",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "getProductInStock",
        "description": "",
        "operationId": "getProductInStock.get.product/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/product": {
      "put": {
        "summary": "createProductInStock",
        "description": "",
        "operationId": "createProductInStock.put.product",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};